services:

  postgres:
    container_name: database
    image: 'postgres:latest'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD:-postgres}
    ports:
      - '5432:5432'
    volumes:
      - ./server/src/main/resources/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - net

  server:
    container_name: server
    build:
      dockerfile: server/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-root}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_PROFILES_ACTIVE=local
      - AWS_REGION=local
      - ENVIRONMENT=local
      - DATASOURCE_USERNAME=${DATASOURCE_USERNAME:-postgres}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD:-root}
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - net

  client:
    container_name: client
    build:
      dockerfile: client/Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - server
    networks:
      - net


networks:
  net:
    driver: bridge